{
  parserClass="com.github.unclepomedev.houdinivexassist.parser.VexParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Vex"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.unclepomedev.houdinivexassist.psi"
  psiImplPackage="com.github.unclepomedev.houdinivexassist.psi.impl"

  elementTypeHolderClass="com.github.unclepomedev.houdinivexassist.psi.VexTypes"
  elementTypeClass="com.github.unclepomedev.houdinivexassist.psi.VexElementType"
  tokenTypeClass="com.github.unclepomedev.houdinivexassist.psi.VexTokenType"

  generateTokenAccessors=true

  tokens=[
    SPACE='regexp:\s+'
    LINE_COMMENT='regexp://.*'
    BLOCK_COMMENT='regexp:/\*([^*]|\*+[^*/])*\*+/'
    NUMBER='regexp:([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?|(0[xX][0-9a-fA-F]+)'
    STRING="regexp:\"[^\"]*\"|'[^']*'"
    UNCLOSED_STRING="regexp:\"[^\r\n\"]*|'[^\r\n']*"
    SYS_STRING="regexp:<[^>]*>"
    UNCLOSED_SYS_STRING="regexp:<[^\r\n>]*"
    ATTRIBUTE="regexp:[fiuvsp34md]?(\\[\\])?@\\w+"
    INCLUDE_KW='regexp:#[ \t]*include'
    DEFINE_KW='regexp:#[ \t]*define'
    PP_IFDEF_KW='regexp:#[ \t]*ifdef'
    PP_IFNDEF_KW='regexp:#[ \t]*ifndef'
    PP_IF_KW='regexp:#[ \t]*if'
    PP_ELIF_KW='regexp:#[ \t]*elif'
    PP_ELSE_KW='regexp:#[ \t]*else'
    PP_ENDIF_KW='regexp:#[ \t]*endif'
    PP_UNDEF_KW='regexp:#[ \t]*undef'
    MACRO_BODY='regexp:[^\r\n]+'
    MACRO='regexp:#.*'
    INT_KW='int'
    FLOAT_KW='float'
    VECTOR_KW='vector'
    VECTOR2_KW='vector2'
    VECTOR4_KW='vector4'
    MATRIX_KW='matrix'
    MATRIX3_KW='matrix3'
    STRING_KW='string'
    VOID_KW='void'
    BSDF_KW='bsdf'
    DICT_KW='dict'
    IDENTIFIER="regexp:[a-zA-Z_]\w*"
    LBRACE="{"
    RBRACE="}"
    LPAREN="("
    RPAREN=")"
    LBRACK="["
    RBRACK="]"
    ARROW="->"
    SEMICOLON=";"
    COMMA=","
    DOT="."
    PLUSEQ="+="
    MINUSEQ="-="
    MULEQ="*="
    DIVEQ="/="
    EQUALS="="
    EQEQ="=="
    NEQ="!="
    LT="<"
    GT=">"
    LE="<="
    GE=">="
    PLUSPLUS="++"
    MINUSMINUS="--"
    PLUS="+"
    MINUS="-"
    MUL="*"
    DIV="/"
    MOD="%"
    ANDAND="&&"
    OROR="||"
    NOT="!"
    QMARK="?"
    COLON=":"
    MODEQ="%="
    ANDEQ="&="
    OREQ="|="
    XOREQ="^="
    LSHIFTEQ="<<="
    RSHIFTEQ=">>="
    LSHIFT="<<"
    RSHIFT=">>"
    BITAND="&"
    BITOR="|"
    BITXOR="^"
    BITNOT="~"
    IF="if"
    ELSE="else"
    FOR="for"
    FOREACH="foreach"
    WHILE="while"
    DO="do"
    BREAK="break"
    CONTINUE="continue"
    RETURN="return"
    STRUCT="struct"
    EXPORT="export"
    FUNCTION="function"
    CHOP_KW='chop'
    COP2_KW='cop2'
    CVEX_KW='cvex'
    DISPLACE_KW='displace'
    FOG_KW='fog'
    IMAGE3D_KW='image3d'
    LIGHT_KW='light'
    SHADOW_KW='shadow'
    SOP_KW='sop'
    SURFACE_KW='surface'
  ]
  extends(".*_expr")=expr
  extends(".*_statement")=statement
}

vexFile ::= item_*

private item_ ::= include_directive | macro_def | preprocessor_directive | MACRO | struct_def | context_def | function_def | statement | COMMENT | fallback_item

include_directive ::= INCLUDE_KW (STRING | UNCLOSED_STRING | SYS_STRING | UNCLOSED_SYS_STRING) { pin=1 mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexIncludeDirectiveMixin" }

macro_def ::= DEFINE_KW IDENTIFIER (LPAREN macro_parameter_list? RPAREN)? MACRO_BODY? {
    pin=1
    implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
    mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexNamedElementImpl"
}

macro_parameter_list ::= IDENTIFIER (COMMA IDENTIFIER)*

preprocessor_directive ::= pp_ifdef | pp_ifndef | pp_if | pp_elif | pp_else | pp_endif | pp_undef
pp_ifdef ::= PP_IFDEF_KW IDENTIFIER { pin=1 }
pp_ifndef ::= PP_IFNDEF_KW IDENTIFIER { pin=1 }
pp_if ::= PP_IF_KW MACRO_BODY? { pin=1 }
pp_elif ::= PP_ELIF_KW MACRO_BODY? { pin=1 }
pp_else ::= PP_ELSE_KW { pin=1 }
pp_endif ::= PP_ENDIF_KW { pin=1 }
pp_undef ::= PP_UNDEF_KW IDENTIFIER { pin=1 }

type_ref ::= primitive_type | IDENTIFIER {
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexTypeRefMixin"
}
private primitive_type ::=
    INT_KW | FLOAT_KW | VECTOR_KW | VECTOR2_KW | VECTOR4_KW |
    MATRIX_KW | MATRIX3_KW | STRING_KW | VOID_KW | BSDF_KW | DICT_KW

private fallback_item ::= NUMBER | STRING | ATTRIBUTE | type_ref
                        | LBRACK | RBRACK | ARROW
                        | SEMICOLON | COMMA | DOT
                        | PLUSEQ | MINUSEQ | MULEQ | DIVEQ | MODEQ | ANDEQ | OREQ | XOREQ | LSHIFTEQ | RSHIFTEQ
                        | EQUALS | EQEQ | NEQ | LT | GT | LE | GE
                        | PLUSPLUS | MINUSMINUS | PLUS | MINUS | MUL | DIV | MOD
                        | LSHIFT | RSHIFT | BITAND | BITOR | BITXOR | BITNOT
                        | ANDAND | OROR | NOT | QMARK | COLON
                        | IF | ELSE | FOR | FOREACH | WHILE | DO | BREAK | CONTINUE | RETURN | STRUCT

struct_def ::= STRUCT IDENTIFIER LBRACE struct_member* RBRACE {
    pin=1
    implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
    mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexNamedElementImpl"
}

struct_member ::= type_ref ( IDENTIFIER ARROW function_signature | declaration_item (COMMA declaration_item)* ) SEMICOLON { pin=1 recoverWhile=struct_member_recover }
private struct_member_recover ::= !(type_ref | RBRACE)

function_signature ::= IDENTIFIER LPAREN parameter_list_sig? RPAREN

CONTEXT_TYPE ::= CHOP_KW | COP2_KW | CVEX_KW | DISPLACE_KW | FOG_KW | IMAGE3D_KW | LIGHT_KW | SHADOW_KW | SOP_KW | SURFACE_KW

context_def ::= CONTEXT_TYPE IDENTIFIER LPAREN parameter_list_def? RPAREN block {
    pin="LPAREN"
    implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
    mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexNamedElementImpl"
}

function_def ::= EXPORT? FUNCTION? type_ref IDENTIFIER LPAREN parameter_list_def? RPAREN block {
    pin="LPAREN"
    implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
    mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexNamedElementImpl"
}

parameter_list_def ::= parameter_def ((COMMA | SEMICOLON) parameter_def)*
parameter_def ::= type_ref IDENTIFIER (LBRACK RBRACK)? BITAND? {
    implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
    mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexNamedElementImpl"
}

parameter_list_sig ::= parameter_sig ((COMMA | SEMICOLON) parameter_sig)*
parameter_sig ::= type_ref IDENTIFIER?

block ::= LBRACE item_* RBRACE

statement ::= block
            | if_statement
            | for_statement
            | foreach_statement
            | while_statement
            | do_while_statement
            | return_statement
            | control_statement
            | declaration_statement
            | expr_statement
            | preprocessor_directive

if_statement ::= IF LPAREN expr RPAREN statement (ELSE statement)? { pin=1 }

for_statement ::= FOR LPAREN for_init expr_statement expr? RPAREN statement { pin=1 }
private for_init ::= declaration_statement | expr_statement

foreach_statement ::= FOREACH LPAREN foreach_body RPAREN statement { pin=1 }
private foreach_body ::= foreach_var SEMICOLON foreach_var SEMICOLON expr
                       | foreach_var COMMA foreach_var SEMICOLON expr
                       | foreach_var SEMICOLON expr
private foreach_var ::= (type_ref IDENTIFIER) | IDENTIFIER

while_statement ::= WHILE LPAREN expr RPAREN statement { pin=1 }
do_while_statement ::= DO statement WHILE LPAREN expr RPAREN SEMICOLON { pin=1 }

return_statement ::= RETURN expr? SEMICOLON { pin=1 }

control_statement ::= (BREAK | CONTINUE) SEMICOLON { pin=1 }

declaration_statement ::= type_ref declaration_item (COMMA declaration_item)* SEMICOLON { pin=2 }
declaration_item ::= IDENTIFIER (LBRACK RBRACK)? (EQUALS expr)? {
    pin=1
    implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
    mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexNamedElementImpl"
}

expr_statement ::= expr SEMICOLON? | SEMICOLON

expr ::= assign_expr
       | ternary_expr
       | logical_or_expr
       | logical_and_expr
       | bitwise_or_expr
       | bitwise_xor_expr
       | bitwise_and_expr
       | equality_expr
       | relational_expr
       | shift_expr
       | add_expr
       | mul_expr
       | cast_expr
       | prefix_expr
       | postfix_expr
       | array_access_expr
       | call_expr
       | type_cast_call_expr
       | member_expr
       | attribute_expr
       | primary_expr

assign_expr ::= expr (EQUALS | PLUSEQ | MINUSEQ | MULEQ | DIVEQ | MODEQ | ANDEQ | OREQ | XOREQ | LSHIFTEQ | RSHIFTEQ) expr { rightAssociative=true }
ternary_expr ::= expr QMARK expr COLON expr { rightAssociative=true }

logical_or_expr ::= expr OROR expr
logical_and_expr ::= expr ANDAND expr

bitwise_or_expr ::= expr BITOR expr
bitwise_xor_expr ::= expr BITXOR expr
bitwise_and_expr ::= expr BITAND expr

equality_expr ::= expr equality_op expr
private equality_op ::= EQEQ | NEQ

relational_expr ::= expr relational_op expr
private relational_op ::= LT | GT | LE | GE

shift_expr ::= expr shift_op expr
private shift_op ::= LSHIFT | RSHIFT

add_expr ::= expr add_op expr
private add_op ::= PLUS | MINUS

mul_expr ::= expr mul_op expr
private mul_op ::= MUL | DIV | MOD

cast_expr ::= LPAREN type_ref RPAREN expr { rightAssociative=true }

prefix_expr ::= prefix_op expr
private prefix_op ::= PLUSPLUS | MINUSMINUS | PLUS | MINUS | NOT | BITNOT

postfix_expr ::= expr postfix_op
private postfix_op ::= PLUSPLUS | MINUSMINUS

array_access_expr ::= expr LBRACK expr RBRACK

call_expr ::= IDENTIFIER LPAREN argument_list? RPAREN {
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexCallExprMixin"
}
type_cast_call_expr ::= primitive_type LPAREN argument_list? RPAREN
member_expr ::= expr DOT IDENTIFIER? {
  pin=2
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexMemberExprMixin"
}
private paren_expr ::= LPAREN expr RPAREN
primary_expr ::= IDENTIFIER | NUMBER | STRING | paren_expr | dict_literal | vector_literal {
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexPrimaryExprMixin"
  implements="com.github.unclepomedev.houdinivexassist.psi.VexNamedElement"
}
attribute_expr ::= ATTRIBUTE {
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexAttributeExprMixin"
}
vector_literal ::= LBRACE argument_list? RBRACE

dict_literal ::= LBRACE [dict_item (COMMA dict_item)*] RBRACE
dict_item ::= expr COLON expr

argument_list ::= expr (COMMA expr)*
