{
  parserClass="com.github.unclepomedev.houdinivexassist.parser.VexParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Vex"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.unclepomedev.houdinivexassist.psi"
  psiImplPackage="com.github.unclepomedev.houdinivexassist.psi.impl"

  elementTypeHolderClass="com.github.unclepomedev.houdinivexassist.psi.VexTypes"
  elementTypeClass="com.github.unclepomedev.houdinivexassist.psi.VexElementType"
  tokenTypeClass="com.github.unclepomedev.houdinivexassist.psi.VexTokenType"

  generateTokenAccessors=true

  tokens=[
    SPACE='regexp:\s+'
    COMMENT='regexp://.*|/\*([^*]|\*+[^*/])*\*+/'
    NUMBER='regexp:([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?|(0[xX][0-9a-fA-F]+)'
    STRING="regexp:\"[^\"]*\"|'[^']*'"
    UNCLOSED_STRING="regexp:\"[^\r\n\"]*|'[^\r\n']*"
    ATTRIBUTE="regexp:[fiuvsp]?(\\[\\])?@\\w+"
    MACRO='regexp:#.*'
    INT_KW='int'
    FLOAT_KW='float'
    VECTOR_KW='vector'
    VECTOR2_KW='vector2'
    VECTOR4_KW='vector4'
    MATRIX_KW='matrix'
    MATRIX3_KW='matrix3'
    STRING_KW='string'
    VOID_KW='void'
    BSDF_KW='bsdf'
    DICT_KW='dict'
    IDENTIFIER="regexp:[a-zA-Z_]\w*"
    LBRACE="{"
    RBRACE="}"
    LPAREN="("
    RPAREN=")"
    LBRACK="["
    RBRACK="]"
    ARROW="->"
    SEMICOLON=";"
    COMMA=","
    DOT="."
    PLUSEQ="+="
    MINUSEQ="-="
    MULEQ="*="
    DIVEQ="/="
    EQUALS="="
    EQEQ="=="
    NEQ="!="
    LT="<"
    GT=">"
    LE="<="
    GE=">="
    PLUSPLUS="++"
    MINUSMINUS="--"
    PLUS="+"
    MINUS="-"
    MUL="*"
    DIV="/"
    MOD="%"
    ANDAND="&&"
    OROR="||"
    NOT="!"
    QMARK="?"
    COLON=":"
    MODEQ="%="
    ANDEQ="&="
    OREQ="|="
    XOREQ="^="
    LSHIFTEQ="<<="
    RSHIFTEQ=">>="
    LSHIFT="<<"
    RSHIFT=">>"
    BITAND="&"
    BITOR="|"
    BITXOR="^"
    BITNOT="~"
    IF="if"
    ELSE="else"
    FOR="for"
    FOREACH="foreach"
    WHILE="while"
    DO="do"
    BREAK="break"
    CONTINUE="continue"
    RETURN="return"
    STRUCT="struct"
    EXPORT="export"
    FUNCTION="function"
  ]
  extends(".*_expr")=expr
  extends(".*_statement")=statement
}

vexFile ::= item_*

private item_ ::= MACRO | struct_def | function_def | statement | COMMENT | fallback_item

type_ref ::= primitive_type | IDENTIFIER
private primitive_type ::=
    INT_KW | FLOAT_KW | VECTOR_KW | VECTOR2_KW | VECTOR4_KW |
    MATRIX_KW | MATRIX3_KW | STRING_KW | VOID_KW | BSDF_KW | DICT_KW

private fallback_item ::= NUMBER | STRING | ATTRIBUTE | type_ref
                        | LBRACK | RBRACK | ARROW
                        | SEMICOLON | COMMA | DOT
                        | PLUSEQ | MINUSEQ | MULEQ | DIVEQ | MODEQ | ANDEQ | OREQ | XOREQ | LSHIFTEQ | RSHIFTEQ
                        | EQUALS | EQEQ | NEQ | LT | GT | LE | GE
                        | PLUSPLUS | MINUSMINUS | PLUS | MINUS | MUL | DIV | MOD
                        | LSHIFT | RSHIFT | BITAND | BITOR | BITXOR | BITNOT
                        | ANDAND | OROR | NOT | QMARK | COLON
                        | IF | ELSE | FOR | FOREACH | WHILE | DO | BREAK | CONTINUE | RETURN | STRUCT

struct_def ::= STRUCT IDENTIFIER LBRACE struct_member* RBRACE { pin=1 }

struct_member ::= type_ref ( IDENTIFIER ARROW function_signature | declaration_item (COMMA declaration_item)* ) SEMICOLON { pin=1 recoverWhile=struct_member_recover }
private struct_member_recover ::= !(type_ref | RBRACE)

function_signature ::= IDENTIFIER LPAREN parameter_list_sig? RPAREN

function_def ::= EXPORT? FUNCTION? type_ref IDENTIFIER LPAREN parameter_list_def? RPAREN block { pin="LPAREN" }

parameter_list_def ::= parameter_def ((COMMA | SEMICOLON) parameter_def)*
parameter_def ::= type_ref IDENTIFIER (LBRACK RBRACK)? BITAND?

parameter_list_sig ::= parameter_sig ((COMMA | SEMICOLON) parameter_sig)*
parameter_sig ::= type_ref IDENTIFIER?

block ::= LBRACE item_* RBRACE

statement ::= block
            | if_statement
            | for_statement
            | foreach_statement
            | while_statement
            | do_while_statement
            | return_statement
            | control_statement
            | declaration_statement
            | expr_statement

if_statement ::= IF LPAREN expr RPAREN statement (ELSE statement)? { pin=1 }

for_statement ::= FOR LPAREN for_init expr_statement expr? RPAREN statement { pin=1 }
private for_init ::= declaration_statement | expr_statement

foreach_statement ::= FOREACH LPAREN foreach_body RPAREN statement { pin=1 }
private foreach_body ::= foreach_var SEMICOLON foreach_var SEMICOLON expr
                       | foreach_var COMMA foreach_var SEMICOLON expr
                       | foreach_var SEMICOLON expr
private foreach_var ::= (type_ref IDENTIFIER) | IDENTIFIER

while_statement ::= WHILE LPAREN expr RPAREN statement { pin=1 }
do_while_statement ::= DO statement WHILE LPAREN expr RPAREN SEMICOLON { pin=1 }

return_statement ::= RETURN expr? SEMICOLON { pin=1 }

control_statement ::= (BREAK | CONTINUE) SEMICOLON { pin=1 }

declaration_statement ::= type_ref declaration_item (COMMA declaration_item)* SEMICOLON { pin=2 }
declaration_item ::= IDENTIFIER (LBRACK RBRACK)? (EQUALS expr)? { pin=1 }

expr_statement ::= expr SEMICOLON? | SEMICOLON

expr ::= assign_expr
       | ternary_expr
       | logical_or_expr
       | logical_and_expr
       | bitwise_or_expr
       | bitwise_xor_expr
       | bitwise_and_expr
       | equality_expr
       | relational_expr
       | shift_expr
       | add_expr
       | mul_expr
       | cast_expr
       | prefix_expr
       | postfix_expr
       | array_access_expr
       | call_expr
       | member_expr
       | primary_expr

assign_expr ::= expr (EQUALS | PLUSEQ | MINUSEQ | MULEQ | DIVEQ | MODEQ | ANDEQ | OREQ | XOREQ | LSHIFTEQ | RSHIFTEQ) expr { rightAssociative=true }
ternary_expr ::= expr QMARK expr COLON expr { rightAssociative=true }

logical_or_expr ::= expr OROR expr
logical_and_expr ::= expr ANDAND expr

bitwise_or_expr ::= expr BITOR expr
bitwise_xor_expr ::= expr BITXOR expr
bitwise_and_expr ::= expr BITAND expr

equality_expr ::= expr equality_op expr
private equality_op ::= EQEQ | NEQ

relational_expr ::= expr relational_op expr
private relational_op ::= LT | GT | LE | GE

shift_expr ::= expr shift_op expr
private shift_op ::= LSHIFT | RSHIFT

add_expr ::= expr add_op expr
private add_op ::= PLUS | MINUS

mul_expr ::= expr mul_op expr
private mul_op ::= MUL | DIV | MOD

cast_expr ::= LPAREN type_ref RPAREN expr { rightAssociative=true }

prefix_expr ::= prefix_op expr
private prefix_op ::= PLUSPLUS | MINUSMINUS | PLUS | MINUS | NOT | BITNOT

postfix_expr ::= expr postfix_op
private postfix_op ::= PLUSPLUS | MINUSMINUS

array_access_expr ::= expr LBRACK expr RBRACK

call_expr ::= IDENTIFIER LPAREN argument_list? RPAREN {
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexCallExprMixin"
}
member_expr ::= expr DOT IDENTIFIER? { pin=2 }
primary_expr ::= IDENTIFIER | NUMBER | STRING | ATTRIBUTE | LPAREN expr RPAREN | vector_literal {
  mixin="com.github.unclepomedev.houdinivexassist.psi.impl.VexPrimaryExprMixin"
}
vector_literal ::= LBRACE argument_list? RBRACE

argument_list ::= expr (COMMA expr)*
