{
  parserClass="com.github.unclepomedev.houdinivexassist.parser.VexParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Vex"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.unclepomedev.houdinivexassist.psi"
  psiImplPackage="com.github.unclepomedev.houdinivexassist.psi.impl"

  elementTypeHolderClass="com.github.unclepomedev.houdinivexassist.psi.VexTypes"
  elementTypeClass="com.github.unclepomedev.houdinivexassist.psi.VexElementType"
  tokenTypeClass="com.github.unclepomedev.houdinivexassist.psi.VexTokenType"

  generateTokenAccessors=true

  tokens=[
    SPACE='regexp:\s+'
    COMMENT='regexp://.*|/\*([^*]|\*+[^*/])*\*+/'
    NUMBER='regexp:\d+(\.\d*)?'
    STRING="regexp:\"[^\"]*\"|'[^']*'"
    ATTRIBUTE="regexp:[fiuvsp]?(\\[\\])?@\\w+"
    MACRO='regexp:#.*'
    TYPE='regexp:int|float|vector2?|vector4|matrix3?|string|void'
    IDENTIFIER="regexp:[a-zA-Z_]\w*"
    LBRACE="{"
    RBRACE="}"
    LPAREN="("
    RPAREN=")"
    SEMICOLON=";"
    COMMA=","
    DOT="."
    PLUSEQ="+="
    MINUSEQ="-="
    MULEQ="*="
    DIVEQ="/="
    EQUALS="="
    EQEQ="=="
    NEQ="!="
    LT="<"
    GT=">"
    LE="<="
    GE=">="
    PLUS="+"
    MINUS="-"
    MUL="*"
    DIV="/"
    MOD="%"
    ANDAND="&&"
    OROR="||"
    NOT="!"
    QMARK="?"
    COLON=":"
    IF="if"
    ELSE="else"
    FOR="for"
    FOREACH="foreach"
    WHILE="while"
    DO="do"
    BREAK="break"
    CONTINUE="continue"
    RETURN="return"
  ]
  extends(".*_expr")=expr
  extends(".*_statement")=statement
}

vexFile ::= item_*

private item_ ::= MACRO | function_def | statement | COMMENT | fallback_item

// TODO: mark as error
private fallback_item ::= IDENTIFIER | NUMBER | STRING | ATTRIBUTE | TYPE
                        | LBRACE | RBRACE | LPAREN | RPAREN | SEMICOLON | COMMA | DOT
                        | PLUSEQ | MINUSEQ | MULEQ | DIVEQ
                        | EQUALS | EQEQ | NEQ | LT | GT | LE | GE
                        | PLUS | MINUS | MUL | DIV | MOD
                        | ANDAND | OROR | NOT | QMARK | COLON
                        | IF | ELSE | FOR | FOREACH | WHILE | DO | BREAK | CONTINUE | RETURN

function_def ::= TYPE IDENTIFIER LPAREN parameter_list? RPAREN block
parameter_list ::= parameter (COMMA parameter)*
parameter ::= TYPE IDENTIFIER
block ::= LBRACE item_* RBRACE

statement ::= block
            | if_statement
            | for_statement
            | foreach_statement
            | while_statement
            | do_while_statement
            | return_statement
            | control_statement
            | declaration_statement
            | expr_statement

if_statement ::= IF LPAREN expr RPAREN statement (ELSE statement)?
for_statement ::= FOR LPAREN expr_statement expr_statement expr? RPAREN statement
foreach_statement ::= FOREACH LPAREN (TYPE? IDENTIFIER COMMA)? TYPE? IDENTIFIER SEMICOLON expr RPAREN statement
while_statement ::= WHILE LPAREN expr RPAREN statement
do_while_statement ::= DO statement WHILE LPAREN expr RPAREN SEMICOLON
return_statement ::= RETURN expr? SEMICOLON
control_statement ::= (BREAK | CONTINUE) SEMICOLON

declaration_statement ::= TYPE declaration_item (COMMA declaration_item)* SEMICOLON
private declaration_item ::= IDENTIFIER (EQUALS expr)?

expr_statement ::= expr? SEMICOLON

expr ::= assign_expr
       | ternary_expr
       | logical_or_expr
       | logical_and_expr
       | equality_expr
       | relational_expr
       | add_expr
       | mul_expr
       | prefix_expr
       | call_expr
       | member_expr
       | primary_expr

assign_expr ::= expr (EQUALS | PLUSEQ | MINUSEQ | MULEQ | DIVEQ) expr { rightAssociative=true }
ternary_expr ::= expr QMARK expr COLON expr { rightAssociative=true }

logical_or_expr ::= expr OROR expr
logical_and_expr ::= expr ANDAND expr
equality_expr ::= expr equality_op expr
private equality_op ::= EQEQ | NEQ
relational_expr ::= expr relational_op expr
private relational_op ::= LT | GT | LE | GE
add_expr ::= expr add_op expr
private add_op ::= PLUS | MINUS
mul_expr ::= expr mul_op expr
private mul_op ::= MUL | DIV | MOD
prefix_expr ::= prefix_op expr
private prefix_op ::= PLUS | MINUS | NOT
member_expr ::= expr DOT IDENTIFIER

primary_expr ::= IDENTIFIER | NUMBER | STRING | ATTRIBUTE | LPAREN expr RPAREN | vector_literal

vector_literal ::= LBRACE argument_list? RBRACE

call_expr ::= IDENTIFIER LPAREN argument_list? RPAREN
argument_list ::= expr (COMMA expr)*
